baseurl = "https://loanzen.github.io/"
languageCode = "en-us"
title = "Tech Behind Loanzen"
theme = "hugo-steam-theme"
disqusShortname = "loanzen"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 10
useSummaryIfNoDescription = "true"

[params]
	title = "Loanzen Engineering"
	subtitle = ""
	copyright = ""

	# You can choose between green, orange, red and blue.
	themecolor = "blue"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Loanzen Technology Private Ltd"
	bio = ""
	description = "Loanzen's Engineering Blog"
	
	# Link your social networks (optional)
	location = "https://loanzen.in"
	twitter = "twitter.com/loanzen_in"
	linkedin = "www.linkedin.com/company/loanzen"
	googleplus = ""
	facebook = "www.facebook.com/loanzen.in/"
	instagram = ""
	github = "loanzen"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
